HW2 Кондаков
bimboterminator/2020-1-Atom-QA-Python-A-Kondakov pull request #2
Opened 2020-10-11 18:05 UTC by bimboterminator

# Домашнее задание №2

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
5 тестов на UI target.my.com
Selenoid а нет

2020-10-16 00:46 UTC, snicks92 commented on hw2/conftest.py
> +                                  desired_capabilities=capabilities)
а говоришь нет селеноида, есть и даже работает

2020-10-16 00:55 UTC, snicks92 requested changes
Хорошая работа, несколько комментов ниже

2020-10-16 00:55 UTC, snicks92 commented on hw2/tests/test_target.py
> +    #@pytest.mark.skip(reason='no need')
давай сразу уберем лишние коменты

2020-10-16 00:55 UTC, snicks92 commented on hw2/ui/locators/basic_locators.py
> +                           '/div/div[4]/div[6]/div/div[4]/div/div[2]/div[1]/div[2]/div/div/div/div[2]/input')
что то больно страшно

2020-10-16 00:55 UTC, snicks92 commented on hw2/ui/pages/company_creation_page.py
> +        path_photo = os.path.dirname(os.path.abspath(__file__)) + "\\new.jpg"
`os.path.join(os.path.abspath(__file__), 'new.jpg')`
иначе ошибка, как минимум потому что я не на винде
E       selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : /Users/i.kirillov/lections/2020-1-Atom-QA-Python-A-Kondakov/hw2/ui/pages\new.jpg
E         (Session info: chrome=85.0.4183.121)

2020-10-16 00:55 UTC, snicks92 commented on hw2/tests/test_target.py
> +        assert self.segment_page.is_present(name) == False
долго думал к чему еще придраться, можно просто `assert not self.segment_page.is_present(name)`

2020-10-16 00:55 UTC, snicks92 commented on hw2/ui/pages/login_page.py
> +    def email_isDisplayed(self):
название метода подразумевает что вернется True/False

2020-10-21 22:05 UTC, bimboterminator commented on hw2/ui/locators/basic_locators.py
> +                           '/div/div[4]/div[6]/div/div[4]/div/div[2]/div[1]/div[2]/div/div/div/div[2]/input')
пофиксил, спасибо за review

2020-10-23 12:59 UTC, snicks92 approved these changes

2020-10-23 12:59 UTC, snicks92 commented
Спасибо, принято

2020-10-23 12:59 UTC, merged