Qa hw3 Кондакрв
bimboterminator/2020-1-Atom-QA-Python-A-Kondakov pull request #4
Opened 2020-10-23 13:46 UTC by bimboterminator

# Домашнее задание №3

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
Тесты api на создание аудиторного сегмента

2020-10-26 22:35 UTC, snicks92 requested changes

2020-10-26 22:35 UTC, snicks92 commented on hw3/tests/test_target.py
> +        assert resp_del.status_code == 204
а если АПИ отдало 204, но на самом деле сегмент не удалился?

2020-10-27 11:10 UTC, bimboterminator commented on hw3/tests/test_target.py
> +        assert resp_del.status_code == 204
Вроде исправил. Спасибо

2020-10-28 14:50 UTC, snicks92 approved these changes

2020-10-28 14:51 UTC, snicks92 commented
теперь ок, за то что сдал после дедлайна оценка 4 из 6

2020-10-28 14:51 UTC, merged